### ISSUE TITLE
The type of `secret` parameters should be `&[u8]`, not `String`

### ISSUE THREAD

**Issue by briansmith** [badboy/nobsign#2]
Here is how one would go about creating a secure key for use with nobsign:

```
fn make_key() -> Result<Vec<u8>, ()> {
     use ring::{digest, rand};
     let key = vec![0u8; digest::SHA1.digest_len];
     try!(rand::fill_secure_random(&mut key[..]));
     Ok(key)
}
```

However, such a secure key won't work because nobsign uses `String` as the type of the secret, and Rust's `String` type only allows UTF-8 encoded values. Rust's insistence on `String` and `&str` being UTF-8 encoded means that they can never be used for storing a secure key.

Because of the weird way that HMAC handles large key sizes, BASE64-encoding the key to store it in a `String` would not be as secure as expected, either.

**Comment by badboy** [comment]
Thanks! I will look how to handle this.
